%% Clear and set-up workspace

% Clear
clear;
close all;
clc;

Lims = sym(cast(1, 'uint64')) ./ sym(cast([1e3 1], 'uint64'));

prettyPlot('xLim', Lims, ...
    'yLim', Lims, ...
    'xLabel', '$x$', ...
    'yLabel', '$y$', ...
    'cBarLabel', '$f\left(x,\,y\right)$', ...
    'ncBarTicks', 5, ...
    'xAxisScale', 'log', ...
    'yAxisScale', 'log', ...
    'plotAspectRatio', [2 1 1], ...
    'useGrid', true, ...
    'useColorBar', true);